FROM node:20-alpine AS base
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

RUN npx prisma generate

RUN npm install -g ts-node-dev typescript

EXPOSE 7777

CMD ["ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]
